---
title: "Biostat 212a Homework 2"
subtitle: "Due Feb 6, 2024 @ 11:59PM"
author: "Yang An and UID: 106332601"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: true
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
engine: knitr
knitr:
  opts_chunk: 
    fig.align: 'center'
    # fig.width: 6
    # fig.height: 4
    message: FALSE
    cache: false
---

## ISL Exercise 4.8.1 (10pts)

1. Using a little bit of algebra, prove that (4.2) is equivalent to (4.3). In other words, the logistic function representation and logit representation for the logistic regression model are equivalent.
**Answer**
$$
\begin{aligned}
\frac{p(X)}{1-p(X)} &= e^{\beta_0 + \beta_1 X} \\
p(X) &= e^{\beta_0 + \beta_1 X} (1-p(X)) \\
p(X) &= e^{\beta_0 + \beta_1 X} - e^{\beta_0 + \beta_1 X} p(X) \\
p(X) + e^{\beta_0 + \beta_1 X} p(X) &= e^{\beta_0 + \beta_1 X} \\
p(X) &= \frac{e^{\beta_0 + \beta_1 X}}{1 + e^{\beta_0 + \beta_1 X}} \\
p(X) &= \frac{1}{1 + e^{-(\beta_0 + \beta_1 X)}}
\end{aligned}
$$


## ISL Exercise 4.8.6 (10pts)
 Suppose we collect data for a group of students in a statistics class with variables X1 = hours studied, X2 = undergrad GPA, and Y = receive an A. We fit a logistic regression and produce estimated coefficient, βˆ0 = −6, βˆ1 = 0.05, βˆ2 = 1.
(a) Estimate the probability that a student who studies for 40 h and has an undergrad GPA of 3.5 gets an A in the class.
(b) How many hours would the student in part (a) need to study to have a 50 % chance of getting an A in the class?
**Answer**
(a)Probability that a student who studies for 40 hours and has an undergrad GPA of 3.5 gets an A in the class is 0.3775.
$$
\begin{aligned}
p(X) &= \frac{1}{1 + e^{-(\beta_0 + \beta_1 X_1 + \beta_2 X_2)}} \\
p(X) &= \frac{1}{1 + e^{-(\beta_0 + \beta_1 40 + \beta_2 3.5)}} \\
p(X) &= \frac{1}{1 + e^{-(-6 + 2.0 + 3.5)}} \\
p(X) &= \frac{1}{1 + e^{-0.5}} \\
p(X) &= \frac{1}{1 + 1.6487} \\
p(X) &= \frac{1}{2.6487} \\
p(X) &= 0.3775
\end{aligned}
$$
(b)the student in part (a) Should need to study 50 hours to have a 50% chance of getting an A in the class.
$$
\begin{aligned}
p(X) &= \frac{1}{1 + e^{-(\beta_0 + \beta_1 X_1 + \beta_2 X_2)}} \\
0.5 &= \frac{1}{1 + e^{-(-6 + 0.05 x_1 + 3.5)}} \\
0.5 &= \frac{1}{1 + e^{2.5 - 0.05 x_1}} \\
1 + e^{2.5 - 0.05 x_1} &= 2 \\
e^{2.5 - 0.05 x_1} &= 1 \\
2.5 - 0.05 x_1 &= 0 \\
0.05 x_1 &= 2.5 \\
x_1 &= 50
\end{aligned}
$$

## ISL Exercise 4.8.9 (10pts)

## ISL Exercise 4.8.13 (a)-(i) (50pts)

## Bonus question: ISL Exercise 4.8.13 Part (j) (30pts)

## Bonus question: ISL Exercise 4.8.4 (30pts)
