<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yang An and UID:106332601">
<meta name="dcterms.date" content="2024-02-15">

<title>Biostat 212A Homework 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw3sol_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw3sol_files/libs/quarto-html/quarto.js"></script>
<script src="hw3sol_files/libs/quarto-html/popper.min.js"></script>
<script src="hw3sol_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw3sol_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw3sol_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw3sol_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw3sol_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw3sol_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw3sol_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  
  <script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#isl-exercise-5.4.2-10pts" id="toc-isl-exercise-5.4.2-10pts" class="nav-link active" data-scroll-target="#isl-exercise-5.4.2-10pts"><span class="header-section-number">1</span> ISL Exercise 5.4.2 (10pts)</a></li>
  <li><a href="#isl-exercise-5.4.9-20pts" id="toc-isl-exercise-5.4.9-20pts" class="nav-link" data-scroll-target="#isl-exercise-5.4.9-20pts"><span class="header-section-number">2</span> ISL Exercise 5.4.9 (20pts)</a></li>
  <li><a href="#least-squares-is-mle-10pts" id="toc-least-squares-is-mle-10pts" class="nav-link" data-scroll-target="#least-squares-is-mle-10pts"><span class="header-section-number">3</span> Least squares is MLE (10pts)</a></li>
  <li><a href="#isl-exercise-6.6.1-10pts" id="toc-isl-exercise-6.6.1-10pts" class="nav-link" data-scroll-target="#isl-exercise-6.6.1-10pts"><span class="header-section-number">4</span> ISL Exercise 6.6.1 (10pts)</a></li>
  <li><a href="#isl-exercise-6.6.11-30pts" id="toc-isl-exercise-6.6.11-30pts" class="nav-link" data-scroll-target="#isl-exercise-6.6.11-30pts"><span class="header-section-number">5</span> ISL Exercise 6.6.11 (30pts)</a></li>
  <li><a href="#bonus-question-20pts" id="toc-bonus-question-20pts" class="nav-link" data-scroll-target="#bonus-question-20pts"><span class="header-section-number">6</span> Bonus question (20pts)</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 212A Homework 3</h1>
<p class="subtitle lead">Due Feb 20, 2024 @ 11:59PM</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yang An and UID:106332601 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 15, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="isl-exercise-5.4.2-10pts" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="isl-exercise-5.4.2-10pts"><span class="header-section-number">1</span> ISL Exercise 5.4.2 (10pts)</h2>
<ol start="2" type="1">
<li>We will now derive the probability that a given observation is part of a bootstrap sample. Suppose that we obtain a bootstrap sample from a set of n observations.</li>
</ol>
<ol type="a">
<li>What is the probability that the first bootstrap observation is not the jth observation from the original sample?</li>
</ol>
<p>The probability that the first bootstrap observation is not the jth observation from the original sample is 1 - 1/n.&nbsp;This is because the probability of the first bootstrap observation being the jth observation from the original sample is 1/n.&nbsp;Therefore, the probability that the first bootstrap observation is not the jth observation from the original sample is 1 - 1/n.</p>
<ol start="2" type="a">
<li>What is the probability that the second bootstrap observation is not the jth observation from the original sample?</li>
</ol>
<p>The probability that the second bootstrap observation is not the jth observation from the original sample is 1 - 1/n.&nbsp;This is because the probability of the second bootstrap observation being the jth observation from the original sample is 1/n.&nbsp;Therefore, the probability that the second bootstrap observation is not the jth observation from the original sample is 1 - 1/n. (c) Argue that the probability that the jth observation is not in the bootstrap sample is (1 − 1/n)^n.</p>
<p>The probability that the jth observation is not in the bootstrap sample is (1 − 1/n)^n.&nbsp;This is because the probability that the first bootstrap observation is not the jth observation from the original sample is 1 - 1/n.&nbsp;The probability that the second bootstrap observation is not the jth observation from the original sample is 1 - 1/n.&nbsp;Therefore, the probability that the jth observation is not in the bootstrap sample is (1 − 1/n)^n.</p>
<ol start="4" type="a">
<li>When n = 5, what is the probability that the jth observation is in the bootstrap sample?</li>
</ol>
<p>When n = 5, the probability that the jth observation is in the bootstrap sample is 1-(1 − 1/5)^5 = 0.67232.</p>
<ol start="5" type="a">
<li>When n = 100, what is the probability that the jth observation is in the bootstrap sample?</li>
</ol>
<p>When n = 100, the probability that the jth observation is in the bootstrap sample is 1-(1 − 1/100)^100 = 0.6339676587267709.</p>
<ol start="6" type="a">
<li>When n = 10, 000, what is the probability that the jth observa- tion is in the bootstrap sample?</li>
</ol>
<p>When n = 10, 000, the probability that the jth observation is in the bootstrap sample is 1-(1 − 1/10,000)^10,000 = 0.6321.</p>
<ol start="7" type="a">
<li>Create a plot that displays, for each integer value of n from 1 to 100,000, the probability that the jth observation is in the bootstrap sample. Comment on what you observe.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>boot1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">n =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100000</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>boot1<span class="sc">$</span>prob <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">1</span><span class="sc">/</span>boot1<span class="sc">$</span>n)<span class="sc">^</span>boot1<span class="sc">$</span>n</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> boot1, <span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> prob)) <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Probability that the jth observation is in the bootstrap sample"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"n"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probability"</span>) <span class="sc">+</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="hw3sol_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows that the probability that the jth observation is in the bootstrap sample decreases as n increases. The probability that the jth observation is in the bootstrap sample is 1 when n = 1, and it decreases to 0.6321 when n = 10,000.</p>
<ol start="8" type="a">
<li>We will now investigate numerically the probability that a boot- strap sample of size n = 100 contains the jth observation. Here j = 4. We repeatedly create bootstrap samples, and each time we record whether or not the fourth observation is contained in the bootstrap sample. Comment on the results obtained.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>boot2 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">10000</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) {</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a> boot2[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">%in%</span> <span class="dv">4</span>) <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(boot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6417</code></pre>
</div>
</div>
<p>The probability that a bootstrap sample of size n = 100 contains the jth observation is 0.6417. This is close to the probability that the jth observation is in the bootstrap sample when n = 100, which is 0.6339676587267709.</p>
</section>
<section id="isl-exercise-5.4.9-20pts" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="isl-exercise-5.4.9-20pts"><span class="header-section-number">2</span> ISL Exercise 5.4.9 (20pts)</h2>
<ol start="9" type="1">
<li>We will now consider the Boston housing data set, from the ISLR2 library.</li>
</ol>
<ol type="a">
<li>Based on this data set, provide an estimate for the population mean of medv. Call this estimate μˆ.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>mean.fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, index) {</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>   X <span class="ot">&lt;-</span> data<span class="sc">$</span>medv[index]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>   medvmean <span class="ot">=</span> <span class="fu">mean</span>(X)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">return</span>(medvmean)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(Boston)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 506  13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean.fn</span>(Boston, <span class="dv">1</span><span class="sc">:</span><span class="dv">506</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.53281</code></pre>
</div>
</div>
<p>The estimate for the population mean of medv is 22.53281.</p>
<ol start="2" type="a">
<li>Provide an estimate of the standard error of μˆ. Interpret this result. Hint: We can compute the standard error of the sample mean by dividing the sample standard deviation by the square root of the number of observations.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>se.fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, index) {</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>   X <span class="ot">&lt;-</span> data<span class="sc">$</span>medv[index]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>   medvse <span class="ot">=</span> <span class="fu">sd</span>(X)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(X))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">return</span>(medvse)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(Boston)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 506  13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">se.fn</span>(Boston, <span class="dv">1</span><span class="sc">:</span><span class="dv">506</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4088611</code></pre>
</div>
</div>
<p>The estimate of the standard error of μˆ is 0.4088611. This means that the sample mean of medv is 0.4088611 away from the population mean of medv.</p>
<ol start="3" type="a">
<li>Now estimate the standard error of μˆ using the bootstrap. How does this compare to your answer from (b)?</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>boot.fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, index) {</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    m <span class="ot">&lt;-</span> <span class="fu">mean</span>(data<span class="sc">$</span>medv[index])</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span> (m)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="fu">boot</span>(Boston, boot.fn, <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston, statistic = boot.fn, R = 1000)


Bootstrap Statistics :
    original       bias    std. error
t1* 22.53281 -0.008232806    0.407299</code></pre>
</div>
</div>
<p>The standard error of μˆ using the bootstrap is 0.407299. This is close to the standard error of μˆ obtained in (b), which is 0.4088611.</p>
<ol start="4" type="a">
<li>Based on your bootstrap estimate from (c), provide a 95 % con- fidence interval for the mean of medv. Compare it to the results obtained using t.test(Boston$medv). Hint: You can approximate a 95 % confidence interval using the formula [μˆ − 2SE(μˆ), μˆ + 2SE(μˆ)].</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Boston<span class="sc">$</span>medv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  Boston$medv
t = 55.111, df = 505, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 21.72953 23.33608
sample estimates:
mean of x 
 22.53281 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>CI.m <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">22.53</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="fl">0.407299</span>, <span class="fl">22.53</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span><span class="fl">0.407299</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>CI.m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.7154 23.3446</code></pre>
</div>
</div>
<p>The 95% confidence interval for the mean of medv using the bootstrap is [21.7154, 23.3446]. The 95% confidence interval for the mean of medv using t.test(Boston$medv) is [21.72953, 23.33608]. The two confidence intervals are very close and the bond of bootstrap is little larger than t test.</p>
<ol start="5" type="a">
<li>Based on this data set, provide an estimate, μˆmed, for the median value of medv in the population.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>median.fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, index) {</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>   X <span class="ot">&lt;-</span> data<span class="sc">$</span>medv[index]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>   medvmedian <span class="ot">=</span> <span class="fu">median</span>(X)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">return</span>(medvmedian)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(Boston)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 506  13</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median.fn</span>(Boston, <span class="dv">1</span><span class="sc">:</span><span class="dv">506</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.2</code></pre>
</div>
</div>
<ol start="6" type="a">
<li>Wenowwouldliketoestimatethestandarderrorofμˆmed.Unfortunately, there is no simple formula for computing the standard error of the median. Instead, estimate the standard error of the median using the bootstrap. Comment on your findings.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>boot.fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, index) {</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    m <span class="ot">&lt;-</span> <span class="fu">median</span>(data<span class="sc">$</span>medv[index])</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span> (m)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boot</span>(Boston, boot.fn, <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston, statistic = boot.fn, R = 1000)


Bootstrap Statistics :
    original   bias    std. error
t1*     21.2 -0.01095   0.3651793</code></pre>
</div>
</div>
<p>The standard error of μˆmed using the bootstrap is 0.3651739. The median of medv is the same of e, which is 21.2.</p>
<ol start="7" type="a">
<li>Based on this data set, provide an estimate for the tenth per- centile of medv in Boston census tracts. Call this quantity μˆ0.1. (You can use the quantile() function.)</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(Boston<span class="sc">$</span>medv, <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  10% 
12.75 </code></pre>
</div>
</div>
<p>The estimate for the tenth percentile of medv in Boston census tracts is 12.75.</p>
<ol start="8" type="a">
<li>Use the bootstrap to estimate the standard error of μˆ0.1. Com- ment on your findings.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>boot.fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, index) {</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    q <span class="ot">&lt;-</span> <span class="fu">quantile</span>(data<span class="sc">$</span>medv[index], <span class="fl">0.1</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span> (q)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boot</span>(Boston, boot.fn, <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston, statistic = boot.fn, R = 1000)


Bootstrap Statistics :
    original  bias    std. error
t1*    12.75  -0.005   0.5048959</code></pre>
</div>
</div>
<p>The standard error of μˆ0.1 using the bootstrap is 0.504859. The tenth percentile of medv is 12.75, which is equal to g.</p>
</section>
<section id="least-squares-is-mle-10pts" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="least-squares-is-mle-10pts"><span class="header-section-number">3</span> Least squares is MLE (10pts)</h2>
<p>Show that in the case of linear model with Gaussian errors, maximum likelihood and least squares are the same thing, and <span class="math inline">\(C_p\)</span> and AIC are equivalent.</p>
</section>
<section id="isl-exercise-6.6.1-10pts" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="isl-exercise-6.6.1-10pts"><span class="header-section-number">4</span> ISL Exercise 6.6.1 (10pts)</h2>
<ol type="1">
<li>We perform best subset, forward stepwise, and backward stepwise selection on a single data set. For each approach, we obtain p + 1 models, containing 0, 1, 2, . . . , p predictors. Explain your answers:</li>
</ol>
<ol type="a">
<li>Which of the three models with k predictors has the smallest training RSS?</li>
</ol>
<p>The best subset selection has the smallest training RSS because it considers all possible models with k predictors and selects the best one. Both forward and backward selection determine models that depend on which predictors they pick first as they iterate toward the kth model, meaning that a poor choice early on cannot be undone.</p>
<ol start="2" type="a">
<li>Which of the three models with k predictors has the smallest test RSS?</li>
</ol>
<p>The best subset selection has the smallest test RSS because it takes into account more models than the other methods</p>
<ol start="3" type="a">
<li>True or False:</li>
</ol>
<ol type="i">
<li><p>The predictors in the k-variable model identified by forward stepwise are a subset of the predictors in the (k+1)-variable model identified by forward stepwise selection.</p></li>
<li><p>The predictors in the k-variable model identified by back- ward stepwise are a subset of the predictors in the (k + 1)- variable model identified by backward stepwise selection.</p></li>
<li><p>The predictors in the k-variable model identified by back- ward stepwise are a subset of the predictors in the (k + 1)- variable model identified by forward stepwise selection.</p></li>
<li><p>The predictors in the k-variable model identified by forward stepwise are a subset of the predictors in the (k+1)-variable model identified by backward stepwise selection.</p></li>
<li><p>The predictors in the k-variable model identified by best subset are a subset of the predictors in the (k + 1)-variable model identified by best subset selection.</p></li>
<li><p>True. Adding one additional predictor to the model with k predictors results in the model with (k+1) predictors.</p></li>
<li><p>True, One predictor is removed from the model with (k+1) predictors to obtain the model with k predictors.</p></li>
<li><p>False The models obtained from forward and backward selection are not directly connected or interlinked.</p></li>
<li><p>False The models obtained from forward and backward selection are not directly connected or interlinked.</p></li>
<li><p>True The model with (k+1) predictors is derived by choosing from a pool of all potential models with (k+1) predictors, meaning it may not include every predictor chosen for the k-variable model. ## ISL Exercise 6.6.3 (10pts)</p></li>
</ol>
<ol start="3" type="1">
<li>Suppose we estimate the regression coefficients in a linear regression model by minimizing 0n  0p  2 yi − β0 − βjxij subject to 0p |βj| ≤ s for a particular value of s. For parts (a) through (e), indicate which j=1</li>
</ol>
<ol type="a">
<li>As we increase s from 0, the training RSS will:</li>
</ol>
<ol type="i">
<li>Increase initially, and then eventually start decreasing in an inverted U shape.</li>
<li>Decrease initially, and then eventually start increasing in a U shape.</li>
<li>Steadily increase.</li>
<li>Steadily decrease.</li>
<li>Remain constant.</li>
</ol>
<ol start="2" type="a">
<li>Repeat (a) for test RSS.</li>
<li>Repeat (a) for variance.</li>
<li>Repeat (a) for (squared) bias.</li>
<li>Repeat (a) for the irreducible error. <strong>Answer</strong></li>
<li><ol start="3" type="i">
<li>Steadily increase. As we gradually increase the value of λ from 0, the βj coefficients are increasingly constrained away from their least squares estimates. Consequently, the model’s flexibility decreases steadily, leading to a consistent rise in the training RSS (Residual Sum of Squares).</li>
</ol></li>
<li><ol start="2" type="i">
<li>Decrease initially, and then eventually start increasing in a U shape. As the value of λ increases from 0, the model’s flexibility decreases, leading to a decrease in the test RSS. However, as λ continues to increase, the model becomes too inflexible, leading to an increase in the test RSS.</li>
</ol></li>
<li><ol start="3" type="i">
<li>Steadily increase. As we progressively raise the value of s from 0, we are loosening the constraints on the βj coefficients, allowing them to approach their least squares estimates. Consequently, the model becomes increasingly flexible, leading to a consistent rise in variance. In other words, as s increases, the model gains more freedom to fit the data closely, but this also tends to introduce more variability in its predictions.</li>
</ol></li>
<li><ol start="3" type="i">
<li>Steadily decrease. As we increment s from 0, we are relaxing the constraints on the βj coefficients, allowing them to approach their least squares estimates. Consequently, the model becomes increasingly flexible, resulting in a gradual reduction in bias. In simpler terms, as s increases, the model gains more freedom to capture the underlying patterns in the data, leading to a decrease in systematic errors or biases in its predictions.</li>
</ol></li>
<li><ol start="22" type="a">
<li>Remain constant. The irreducible error is the error that cannot be reduced by any model, no matter how complex or flexible. As such, it remains constant regardless of the value of s. ## ISL Exercise 6.6.4 (10pts)</li>
</ol></li>
</ol>
<ol start="4" type="1">
<li>Suppose we estimate the regression coefficients in a linear regression model by minimizing 0n 0p 2 0p yi−β0− βjxij +λ βj2 i=1 j=1 j=1 for a particular value of λ. For parts (a) through (e), indicate which of i. through v. is correct. Justify your answer.</li>
</ol>
<ol type="a">
<li>As we increase λ from 0, the training RSS will:</li>
</ol>
<ol type="i">
<li>Increase initially, and then eventually start decreasing in an inverted U shape.</li>
<li>Decrease initially, and then eventually start increasing in a U shape.</li>
<li>Steadily increase.</li>
<li>Steadily decrease.</li>
<li>Remain constant.</li>
</ol>
<ol start="2" type="a">
<li>Repeat (a) for test RSS. (c) Repeat (a) for variance.</li>
<li>Repeat (a) for (squared) bias.</li>
<li>Repeat (a) for the irreducible error. <strong>Answer</strong></li>
<li><ol start="3" type="i">
<li>Steadily increase. Steadily increase. As we increase λ from 0, we are restricting the βj coefficients more and more (the coefficients will deviate from their least squares estimates), and so the model is becoming less and less flexible which provokes a steady increase in training RSS.</li>
</ol></li>
<li><ol start="2" type="i">
<li>Decrease initially, and then eventually start increasing in a U shape. As λ increases from 0, the model becomes less flexible, leading to a decrease in test RSS. However, as λ continues to increase, the model becomes too inflexible, leading to an increase in test RSS.</li>
</ol></li>
<li><ol start="3" type="i">
<li>Steadily decrease. As we elevate λ from 0, we are imposing greater constraints on the βj coefficients, causing them to deviate increasingly from their least squares estimates. Consequently, the model becomes less flexible, leading to a steady decrease in variance. In simpler terms, increasing λ restricts the model’s ability to vary widely in response to small changes in the training data, resulting in a more stable and less variable model.</li>
</ol></li>
<li><ol start="3" type="i">
<li>Steadily decrease. As we increase λ from 0, we are imposing tighter constraints on the βj coefficients, causing them to deviate further from their least squares estimates. Consequently, the model becomes less flexible, leading to a steady increase in bias. In other words, as λ increases, the model’s ability to capture complex relationships in the data diminishes, resulting in a systematic underestimation or overestimation of the true relationship between the predictors and the response variable.</li>
</ol></li>
<li><ol start="22" type="a">
<li>Remain constant. The irreducible error is the error that cannot be reduced by any model, no matter how complex or flexible. As such, it remains constant regardless of the value of λ. ## ISL Exercise 6.6.5 (10pts)</li>
</ol></li>
</ol>
</section>
<section id="isl-exercise-6.6.11-30pts" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="isl-exercise-6.6.11-30pts"><span class="header-section-number">5</span> ISL Exercise 6.6.11 (30pts)</h2>
<p>You must follow the <a href="https://ucla-econ-425t.github.io/2023winter/slides/06-modelselection/workflow_lasso.html">typical machine learning paradigm</a> to compare <em>at least</em> 3 methods: least squares, lasso, and ridge. Report final results as</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Method</th>
<th style="text-align: center;">CV RMSE</th>
<th style="text-align: center;">Test RMSE</th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">LS</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">Ridge</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Lasso</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">…</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
<section id="bonus-question-20pts" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="bonus-question-20pts"><span class="header-section-number">6</span> Bonus question (20pts)</h2>
<p>Consider a linear regression, fit by least squares to a set of training data <span class="math inline">\((x_1, y_1), \ldots, (x_N, y_N)\)</span> drawn at random from a population. Let <span class="math inline">\(\hat \beta\)</span> be the least squares estimate. Suppose we have some test data <span class="math inline">\((\tilde{x}_1, \tilde{y}_1), \ldots, (\tilde{x}_M, \tilde{y}_M)\)</span> drawn at random from the same population as the training data. If <span class="math inline">\(R_{\text{train}}(\beta) = \frac{1}{N} \sum_{i=1}^N (y_i - \beta^T x_i)^2\)</span> and <span class="math inline">\(R_{\text{test}}(\beta) = \frac{1}{M} \sum_{i=1}^M (\tilde{y}_i - \beta^T \tilde{x}_i)^2\)</span>. Show that <span class="math display">\[
\operatorname{E}[R_{\text{train}}(\hat{\beta})] &lt; \operatorname{E}[R_{\text{test}}(\hat{\beta})].
\]</span></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>